project:
  type: website

website:
  title: "Aryhnr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: PSDtugasdata2.ipynb
        text: PSD
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



